# I'm not sure what to do on this file

title: thacuber2a03
url: https://thacuber2a03.github.io
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
